# Generated by Django 5.1.7 on 2025-04-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('nippnpn', models.CharField(max_length=20)),
                ('tanggal', models.DateTimeField()),
                ('rincian', models.TextField()),
                ('tautan_dakung', models.URLField(max_length=2000)),
                ('progress', models.TextField(blank=True, null=True)),
                ('masalah_hambatan', models.TextField(blank=True, null=True)),
                ('kriteria', models.CharField(choices=[('biasa', 'Biasa'), ('diskusi', 'Perlu Diskusi')], default='biasa', max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['nippnpn', '-created_at'],
            },
        ),
    ]
