# Generated by Django 5.1.7 on 2025-04-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook_ppnpn', '0002_alter_catatan_masalah_hambatan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catatan',
            name='tanggal',
            field=models.DateField(),
        ),
    ]
